const COURSES_DATA = {
  dependencies: {
    "Química General I": [],
    "Matemáticas I": [],
    "Biología Celular I": [],
    "Inglés I": [],
    "Introducción a la Farmacia": [],
    "Química General II": ["Química General I"],
    "Matemáticas II": ["Matemáticas I"],
    Física: ["Matemáticas I"],
    Morfología: ["Biología Celular I"],
    "Inglés II": ["Inglés I"],
    "Química Orgánica I": ["Química General II"],
    "Físico Química I": ["Química General II", "Matemáticas II"],
    Bioestadística: ["Matemáticas II"],
    Fisiología: ["Morfología"],
    "Inglés III": ["Inglés II"],
    "Química Orgánica II": ["Química Orgánica I"],
    "Físico Química II": ["Físico Química I"],
    "Química Analítica": ["Química General II"],
    Fisiopatología: ["Fisiología"],
    "Inglés IV": ["Inglés III"],
    Bioquímica: ["Química Orgánica II", "Físico Química II"],
    "Botánica y Fitoterapia": ["Química Orgánica II"],
    Farmacodinamia: ["Fisiopatología"],
    "Análisis Instrumental": ["Química Analítica"],
    Economía: ["Bioestadística"],
    "Fármaco Química I": ["Química Orgánica II", "Farmacodinamia"],
    "Farmacología I": ["Farmacodinamia"],
    "Microbiología e Inmunología": ["Bioquímica"],
    "Bioquímica Clínica": ["Fisiopatología", "Bioquímica"],
    "Legislación Farmacéutica": [
      "Inglés I",
      "Introducción a la Farmacia",
      "Matemáticas I",
      "Química General I",
      "Biología Celular I",
    ],
    "Gestión Farmacéutica": ["Economía"],
    "Fármaco Química II": ["Fármaco Química I"],
    "Farmacología II": ["Farmacología I"],
    Toxicología: ["Fisiopatología", "Farmacodinamia"],
    "Salud Pública": ["Microbiología e Inmunología", "Economía"],
    "Biofarmacia y Farmacocinética": ["Farmacología I"],
    Ética: ["Legislación Farmacéutica", "Gestión Farmacéutica"],
    "Tecnología Farmacéutica I": ["Biofarmacia y Farmacocinética"],
    "Farmacia Asistencial": ["Salud Pública"],
    "Química de Alimentos": ["Farmacología II"],
    Nutrición: ["Biofarmacia y Farmacocinética"],
    "Electivo II": ["Ética"],
    "Tecnología Farmacéutica II": ["Tecnología Farmacéutica I"],
    "Tecnología Cosmética": ["Tecnología Farmacéutica I"],
    "Unidad de Investigación": [],
    "Farmacia Clínica": ["Farmacología II", "Farmacia Asistencial"],
    "Electivo III": ["Electivo I"],
    "Internado en Farmacia Clínica": [
      "Tecnología Farmacéutica II",
      "Farmacia Clínica",
      "Unidad de Investigación",
      "Tecnología Cosmética",
    ],
    "Práctica Prolongada": [
      "Tecnología Farmacéutica II",
      "Farmacia Clínica",
      "Unidad de Investigación",
      "Tecnología Cosmética",
    ],
    "Práctica Obligatoria en Farmacia Comunitaria": [
      "Inglés I",
      "Introducción a la Farmacia",
      "Matemáticas I",
      "Química General I",
      "Biología Celular I",
      "Física",
      "Matemáticas II",
      "Química General II",
    ],
    "Seminario de Título": [
      "Tecnología Farmacéutica II",
      "Farmacia Clínica",
      "Unidad de Investigación",
      "Tecnología Cosmética",
    ],
  },
  unlocks: {}, // esto lo genera automáticamente el script.js en tiempo real
};
